### ISSUE TITLE
Cookie file not found

### ISSUE THREAD

**Issue by DigitalGiorgiAptsiauri** [ThreeGiantNoobs/chegg-scraper#13]
No matter where I put `cookie.txt `file, it keeps telling me:

```
Traceback (most recent call last):
  File "Downloader.py", line 1, in <module>
    from cheggscraper import Downloader
  File "/mnt/c/Users/Username/OneDrive/Desktop/solutions/cheggscraper/Downloader.py", line 48
    raise Exception(f'{args["cookie_file"]} does not exists')
```

Also tried Downloader.py in the root folder of the project. And using the -c argument. Nothing works
Any idea?

**Comment by k4anubhav** [comment]
Can you try with the latest release? I just publish it.

if the error still persists I am here to help.

**Comment by DigitalGiorgiAptsiauri** [comment]
Just tried that, same problem.

This what my directory looks like:
![image](https://user-images.githubusercontent.com/76108988/122102240-495f6600-ce26-11eb-802d-da4593d3972a.png)

inside `cheggscraper`
![image](https://user-images.githubusercontent.com/76108988/122102275-511f0a80-ce26-11eb-8cd8-26ced3fc5acc.png)

console output:
![image](https://user-images.githubusercontent.com/76108988/122102398-6c8a1580-ce26-11eb-934a-a8b69c942ea5.png)

So, same problem persists

**Comment by k4anubhav** [comment]
Our code only works with python 3.x

try with `python3 Downloader.py`

**Comment by k4anubhav** [comment]
Btw That's Correct the location you need to put `cookie.txt`

![image](https://user-images.githubusercontent.com/75440539/122103324-1de37800-ce34-11eb-88a5-bcf5f2e9a8e1.png)

**Comment by DigitalGiorgiAptsiauri** [comment]
With Python 3. I had to install `importlib-resources`
then in Downloader.py and CheggScraper.py, I changed importlib.resources to importlib_resources and everything worked.

**Comment by DigitalGiorgiAptsiauri** [comment]
By the way, is there a chance, you could implement such functionality:

You would give the program the link to the first problem in a textbook, then program clicks "next" button and downloads each individual problem. 
This would scrape the entire textbook solutions

**Comment by k4anubhav** [comment]
> By the way, is there a chance, you could implement such functionality:
> 
> You would give the program the link to the first problem in a textbook, then program clicks "next" button and downloads each individual problem.
> This would scrape the entire textbook solutions

It's possible, but we need to take sleep btw every new page otherwise it will be flagged as a bot,
So it will not be fast, but still faster than manual.

But it is really good functionality, I will add that soon.

If you flagged as a bot, you need to change the cookie 
or open the same browser where you take that cookie and fill the captcha, and you will be fine.

**Comment by DigitalGiorgiAptsiauri** [comment]
Yes, got it. Of course, some random intervals between transitioning to a new problem

**Comment by k4anubhav** [comment]
> With Python 3. I had to install `importlib-resources`
> then in Downloader.py and CheggScraper.py, I changed importlib.resources to importlib_resources and everything worked.

Can you share your python3 version?

**Comment by DigitalGiorgiAptsiauri** [comment]
> 
> 
> > With Python 3. I had to install `importlib-resources`
> > then in Downloader.py and CheggScraper.py, I changed importlib.resources to importlib_resources and everything worked.
> 
> Can you share your python3 version?

Python 3.6.12

**Comment by k4anubhav** [comment]
Just for info, you don't need to register your device in the browser, from where you get those cookies.
