### ISSUE TITLE
Need Help Regarding using this project with discord or telegram bot

### ISSUE THREAD

**Issue by dishantiit** [ThreeGiantNoobs/chegg-scraper#14]
Sir,
I am a student of IIT Varanasi, and I am a noob in python. I just started learning it.
I want help in making a telegram or discord bot that uses the scripts and returns the answer to the user.
It would be very kind for you to help me.
Thank You

**Comment by Ravi-Akagra** [comment]
Can you please share your progress?
Like, How much you know using python and python libraries? Have you ever made a Discord bot earlier or not? And How much experience you have with some other programming language?

I will assist you with the resources accordingly.

**Comment by dishantiit** [comment]
> Can you please share your progress?
> Like, How much you know using python and python libraries? Have you ever made a Discord bot earlier or not? And How much experience you have with some other programming language?
> 
> I will assist you with the resources accordingly.

I am a beginner and I am learning python from 100 Days of Code Python Bootcamp(From Udemy) and I am on day 4. I haven't even reached loops yet and I have never made any Discord/Telegram bot

**Comment by Ravi-Akagra** [comment]
> I am a beginner, and I am learning python from 100 Days of Code Python Bootcamp(From Udemy), and I am on day 4. I haven't even reached loops yet, and I have never made any Discord/Telegram bot.
> And Institute is teaching us C Programming language, I am good at the subject, but as you know, the institute teaches beginner level stuff to 1st-year students.

Well, in that case, I'll suggest you to attend your Bootcamp and explore this beautiful programming language called Python. In general, for making any bot, You need to have a good grasp of using External Libraries and Exception Handling, and topics like Strings, Lists, and Loops should be on fingertips. I'll suggest you to attend your classes for like 15-20 days and learn some basics of using functions in python and start by making a basic Discord bot that sends Hello world on a channel on command.

**Comment by dishantiit** [comment]
> > I am a beginner, and I am learning python from 100 Days of Code Python Bootcamp(From Udemy), and I am on day 4. I haven't even reached loops yet, and I have never made any Discord/Telegram bot.
> > And Institute is teaching us C Programming language, I am good at the subject, but as you know, the institute teaches beginner level stuff to 1st-year students.
> 
> Well, in that case, I'll suggest you to attend your Bootcamp and explore this beautiful programming language called Python. In general, for making any bot, You need to have a good grasp of using External Libraries and Exception Handling, and topics like Strings, Lists, and Loops should be on fingertips. I'll suggest you to attend your classes for like 15-20 days and learn some basics of using functions in python and start by making a basic Discord bot that sends Hello world on a channel on command.




Ok sir, I will be in contact once I have completed the above-mentioned topics. Thank you for your time.

**Comment by Ravi-Akagra** [comment]
If you face any doubts while learning Python, feel free to mail me at `akagraravi@threegiantnoobs.ml` or the Team at `admin@threegiantnoobs.ml`.

We'll try our best to help you out.

Happy Learning
