### ISSUE TITLE
The template has some problem

### ISSUE THREAD

**Issue by 2838778326** [ThreeGiantNoobs/chegg-scraper#16]
Can you update it

**Comment by k4anubhav** [comment]
Can you please explain?

**Comment by 2838778326** [comment]
The css resource is missing after the html file is generated, and the page looks abnormal

**Comment by 2838778326** [comment]
> Can you please explain the issue?

The css resource is missing after the html file is generated, and the page looks abnormal

**Comment by k4anubhav** [comment]
If your issue is still not solved, feel free to reopen the issue
