### ISSUE TITLE
Some url can't work on  it

### ISSUE THREAD

**Issue by mMitchGraham** [ThreeGiantNoobs/chegg-scraper#22]
https://www.chegg.com/homework-help/questions-and-answers/babies-birth-weights-normally-distributed-mean-120-ounces-standard-deviation-20-ounces-low-q21343037

https://www.chegg.com/homework-help/questions-and-answers/4-consider-gambler-s-ruin-problem-p-04-n-6-starting-state-3-determine-expected-amount-time-q40590496

https://www.chegg.com/homework-help/questions-and-answers/suppose-swing-ball-mass-m-vertical-circle-string-length-l--probably-know-experience-minimu-q2979048

**Comment by k4anubhav** [comment]
Can you share the raw Html for these questions from logs: `scraper.log`

Don't upload the whole `scraper.log`, it logs cookie

**Comment by DevKish0n** [comment]
[qestion.txt](https://github.com/ThreeGiantNoobs/chegg-scraper/files/7514679/qestion.txt)

I have got the same problem. Can you please look at it?

**Comment by k4anubhav** [comment]
and what's the error message.

**Comment by DevKish0n** [comment]
line 16, in main file_saved_path = chegg.url_to_html(url=question_url, file_name_format=default_save_file_format),
line 521, in url_to_html headers, heading, question_div, answers__, question_uuid = self._parse(html_text=html_res_text,
line 455, in _parse answers_div = self._parse_answer(soup, questionUuid, html_text, url, chapter_type=chapter_type),
 line 369, in _parse_answer return self.render_chapter_type_html(res_data),
line 122, in render_chapter_type_html solutionV2 = problem_d['solutionV2'][0]


IndexError: list index out of range


These are the errors.

**Comment by k4anubhav** [comment]
Ohh, that question is not solved

**Comment by DevKish0n** [comment]
Ohh, I see. Thanks, buddy!
