### ISSUE TITLE
Bro do you face reCaptcha error too?

### ISSUE THREAD

**Issue by Jooguuy** [ThreeGiantNoobs/chegg-scraper#24]
Hi guys, codes works good but some of the URL doesn't work.... I mean unless you open them first and pass reCaptcha stuff. Have you faced same issues? or the problem is on my side? Thanks

**Comment by k4anubhav** [comment]
Well, I can't test the code, I don't have a Chegg account anymore.

**Comment by Jooguuy** [comment]
> Well, I can't test the code, I don't have a Chegg account anymore.

ok

**Comment by Nitin-440** [comment]
Captcha error too much
