### ISSUE TITLE
Bot Flag Error when deployed to heroku

### ISSUE THREAD

**Issue by JacobChamie** [ThreeGiantNoobs/chegg-scraper#25]
code works when running on local computer, however when deployed to heroku or any site: AWS, GCP, pythonanywhere etc... I get bot flagged error even with cookie file.

**Comment by Jooguuy** [comment]
> code works when running on local computer, however when deployed to heroku or any site: AWS, GCP, pythonanywhere etc... I get bot flagged error even with cookie file.

same error too

**Comment by PrathakGarg** [comment]
Chegg realises that you are sending requests through a datacenter or a suspicious IP so it blocks the request. Try setting up a VPN

**Comment by arkanalexei** [comment]
> Chegg realises that you are sending requests through a datacenter or a suspicious IP so it blocks the request. Try setting up a VPN

Can you elaborate more on how to solve this issue?

**Comment by JacobChamie** [comment]
> > Chegg realises that you are sending requests through a datacenter or a suspicious IP so it blocks the request. Try setting up a VPN
> 
> Can you elaborate more on how to solve this issue?

I ended up fixing issue using a proxy. First I used proxy to log into chegg account on browser. Then I copied cookies, and used the same proxy when I launched the app on heroku. Ended up working but my proxy provider banned me. To make this work either pay for proxy provider or host it yourself on a raspberry pi

**Comment by arkanalexei** [comment]
> > > Chegg realises that you are sending requests through a datacenter or a suspicious IP so it blocks the request. Try setting up a VPN
> > 
> > 
> > Can you elaborate more on how to solve this issue?
> 
> I ended up fixing issue using a proxy. First I used proxy to log into chegg account on browser. Then I copied cookies, and used the same proxy when I launched the app on heroku. Ended up working but my proxy provider banned me. To make this work either pay for proxy provider or host it yourself on a raspberry pi

Dude, can I talk to you personally like on Discord? I have some questions to ask. My discord: makaveli#9576

**Comment by Jooguuy** [comment]
> raspberry

would you talk to me in discord please?  PrettyBoyFriend#3438
