### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Rus1010** [ThreeGiantNoobs/chegg-scraper#26]
Hi guys, I face the attribute error. I am wondering about how to fix that. Can you guys help me to have a look? Thank you
![Screenshot 2022-01-18 204623](https://user-images.githubusercontent.com/97233216/149940012-63349155-5635-4e2c-aef3-2632ceba5c09.png)

**Comment by k4anubhav** [comment]
You have Chegg paid account right?

**Comment by PrathakGarg** [comment]
Closing the issue because of inactivity

**Comment by Ednn0nd1au** [comment]
Same issue happened
https://github.com/ThreeGiantNoobs/chegg-scraper/issues/31
