### ISSUE TITLE
Chegg account keeps getting suspended

### ISSUE THREAD

**Issue by arkanalexei** [ThreeGiantNoobs/chegg-scraper#27]
Have my own subscription, and I don't share with anyone. Launched the bot on the same browser, same IP as my chegg account and I still get that prompt a day or so after launching the bot. How to fix?

**Comment by k4anubhav** [comment]
How many questions do you ask per day? and are their some spikes in usage?

**Comment by arkanalexei** [comment]
> How many questions do you ask per day? and are there some spikes in usage?
I could not say for certain but definitely a lot. And yes, definitely some spikes in usage as well.  Is there a workaround for this? Perhaps using 2-3 alternating accounts to prevent them from getting suspended?

**Comment by k4anubhav** [comment]
yes there is, use 2-3 alternating accounts, you can also use 2-3 proxies/diff ips as well

**Comment by arkanalexei** [comment]
How long should these 2-3 alternating accounts alternate? 3 hours each? 2 hours?

**Comment by k4anubhav** [comment]
Well, I haven't tested much, but I would prefer to use the alternate account for every alternating request.

it will help to prevent a ban from peaks.

**Comment by arkanalexei** [comment]
I don't know if that would work because our community is large and uses the BOT quite often. Hence, if we alternate per question it would just seem like we ran all the bot at once. Wouldn't you agree?

**Comment by k4anubhav** [comment]
but according to me, Chegg bans when there is a pretty huge spike in usage or if you ask more than x question in a day.

**Comment by arkanalexei** [comment]
Can i ask how big your server is or how many questions your server asks in a day?

**Comment by k4anubhav** [comment]
no

**Comment by arkanalexei** [comment]
lol okay

**Comment by avtar312** [comment]
Can u help me how to use in discord bot
