### ISSUE TITLE
How to change the saved html directory?

### ISSUE THREAD

**Issue by Raymond9266** [ThreeGiantNoobs/chegg-scraper#28]
Hi, after entered the url, the converted html is saved in the same directory as the chegg-scraper file. How do i change the file directory to other place? Thanks

**Comment by k4anubhav** [comment]
`-s` or `--save` to specify file path
example: `\var\www\something.html`
example: `\var\www\{heading}.html`
example: `\var\www\{question_uuid}.html`

**Comment by k4anubhav** [comment]
I think this solves your issue, if not please feel free to reopen issue
