### ISSUE TITLE
Bot Error Flag on home internet connection

### ISSUE THREAD

**Issue by 33masterman33** [ThreeGiantNoobs/chegg-scraper#29]
I have a paid chegg account but every time I try to use the scrapper on my laptop I get the following error "cheggscraper.Exceptions.BotFlagError"

**Comment by PrathakGarg** [comment]
<Duplicate>
https://github.com/ThreeGiantNoobs/chegg-scraper/issues/25

**Comment by 33masterman33** [comment]
How is me having this issue on a standard home internet connection that I can access chegg loads from the website a duplicate of them blocking datacenter ips? I am having this issue when trying to run it on my own computer not hosted somewhere else which the other issue said worked for them.
