### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Ednn0nd1au** [ThreeGiantNoobs/chegg-scraper#31]
Hi there,

After giving the link: https://www.chegg.com/homework-help/questions-and-answers/us-government-recently-announced-started-implement-large-scale-fiscal-expansion-mitigate-n-q91031911?trackid=2e28bc4b1bcc&strackid=0708d012927e, the programme failed with the following error:

root@78:/codingProject/chegg-scraper# python3 Downloader.py -u https://www.chegg.com/homework-help/questions-and-answers/us-government-recently-announced-started-implement-large-scale-fiscal-expansion-mitigate-n-q91031911?trackid=2e28bc4b1bcc&strackid=0708d012927e
[16] 42052
root@78:/codingProject/chegg-scraper# Traceback (most recent call last):
  File "Downloader.py", line 3, in <module>
    Downloader.main()
  File "/codingProject/chegg-scraper/cheggscraper/Downloader.py", line 40, in main
    print(Chegg.url_to_html(args['url'], file_name_format=args['file_format']))
  File "/codingProject/chegg-scraper/cheggscraper/CheggScraper.py", line 521, in url_to_html
    headers, heading, question_div, answers__, question_uuid = self._parse(html_text=html_res_text,
  File "/codingProject/chegg-scraper/cheggscraper/CheggScraper.py", line 437, in _parse
    re.search(r'C\.page\.homeworkhelp_question\((.*)?\);', html_text).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Ednn0nd1au** [comment]
@04anubhavv 
@k4anubhav

**Comment by Jason-S-Wu** [comment]
Chegg changed the way answers are received to use a new API, which is most likely the source of the parsing problem.


Example Question: https://www.chegg.com/homework-help/questions-and-answers/1-1-q86866225

```
URL: https://gateway.chegg.com/one-graph/graphql
Method: POST
Data: {
   "operationName":"QnaPageQuestionByLegacyId",
   "variables":{
      "id":86866225
   },
   "extensions":{
      "persistedQuery":{
         "version":1,
         "sha256Hash":"THIS_MIGHT_BE_STATIC_VALUE"
      }
   }
}
```

Chegg appears to be in the process of upgrading the chapter questions to use the new endpoint as well. Also based on the `operationName` in the post data, they are probably going to make further changes in the future.

**Comment by Ednn0nd1au** [comment]
@Jason-S-Wu Hi Jason, thank you so much for explaining this. An invitation from discord just send, shall I DM you for further information please.
