### ISSUE TITLE
Captcha Error

### ISSUE THREAD

**Issue by kevincrack9bit** [ThreeGiantNoobs/chegg-scraper#38]
Chegg detects the script as a bot and asks to resolve the captcha after 2 links, any solution?  I have changed the UserAgent correctly in the configuration file.

**Comment by kevincrack9bit** [comment]
Maybe you can solve this problem by using a list of proxies ?

**Comment by Nitin-440** [comment]
> Maybe you can solve this problem by using a list of proxies ?

How
