### ISSUE TITLE
Help(CAN PAY FOR IT)

### ISSUE THREAD

**Issue by DangBoyuu** [ThreeGiantNoobs/chegg-scraper#9]
Ey, can you help someone like me who has no idea about using python? 
I need to have chegg bot into my server! and I'm willing to pay for this help! THANKS

**Comment by PrathakGarg** [comment]
Do you have a paid Chegg account? If yes, you can contact us for further discussion on said bot

**Comment by DangBoyuu** [comment]
I can buy it, it's 14.95$ right?

**Comment by PrathakGarg** [comment]
Yeah. You'll need a subscribed account for the bot to function. For further communication, you can send a mail to admin@threegiantnoobs.ml

**Comment by DangBoyuu** [comment]
Ok, I will send email to you now!
